branches:
  only:
    - master
    - 1.2.1

language: bash

services:
  - docker

before_install:
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"

before_script:
  - repo=gvirtu/fakes3-alpine
  - builddate=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
  - buildrev=$(git rev-parse --short HEAD)

script:
  - docker build --build-arg VCS_REF=$buildrev --build-arg BUILD_DATE=$builddate -t $repo .
  - docker run --rm $repo fakes3 --help

after_success:
  - tag=$(docker run --rm $repo /bin/sh -c 'echo $FAKES3_VERSION')
  - docker tag $repo $repo:$tag
  - docker push $repo:latest
  - docker push $repo:$tag
